import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import mongoose from 'mongoose';
import {MongoMemoryServer} from 'mongodb-memory-server';
import express from 'express';
import request from 'supertest';
import {inspectDirectory,buildRecords,normalize,locationKey} from './importer.js';
import {createOmanDataService} from './service.js';
import {StructuredOmanRecord,StructuredOmanState} from '../../Models/StructuredOmanData.js';
import {createOmanDataRouter} from '../../routes/omanData.js';
import {buildSmartAssistantRequest} from '../../utils/buildSmartAssistantRequest.js';
import {RIADATECH_SYSTEM_PROMPT} from '../../prompts/riadaTechSystemPrompt.js';
let mongo,conn,Record,State,dir,service;
before(async()=>{mongo=await MongoMemoryServer.create();conn=await mongoose.createConnection(mongo.getUri()).asPromise();Record=conn.model('Record',StructuredOmanRecord.schema);State=conn.model('State',StructuredOmanState.schema);dir=await fs.mkdtemp(path.join(os.tmpdir(),'oman-data-'));await fs.writeFile(path.join(dir,'عينة.csv'),'governorate,wilayat,activity,count\nمحافظة مسقط,بوشـر,تجارة,2\nمحافظة مسقط,بوشـر,تجارة,\nمحافظة مسقط,بوشـر,تجارة,0\n');service=createOmanDataService({Record,State,directory:dir});});
after(async()=>{await conn?.close();await mongo?.stop();if(dir)await fs.rm(dir,{recursive:true});});
test('Unicode normalization preserves originals and missing values',async()=>{assert.equal(normalize('إبـراء عُمان'),'ابراء عمان');assert.equal(locationKey(' محافظة مسقط '),'مسقط');const scan=await inspectDirectory(dir);const {records}=buildRecords(scan);assert.equal(records.length,3);assert.equal(records[0].dimensions.wilayat.original,'بوشـر');assert.equal(records[0].dimensions.wilayat.normalized,'بوشر');assert.equal(records[1].fields[3].value,'');assert.equal(records[2].fields[3].value,'0');});
test('real workbooks: all sheets, duplicate files, repeated entity rows, periods and totals',async()=>{const scan=await inspectDirectory();const {records,aliases}=buildRecords(scan);assert.equal(scan.files.length,11);assert.equal(scan.datasets.length,10);assert.equal(records.length,64945);assert.equal(records.filter(r=>r.datasetType==='women_entrepreneurs').length,16274);assert.equal(records.filter(r=>r.isTotal).length,1);assert.equal(records.filter(r=>r.datasetType==='home_business_licenses').length,7965);assert.equal(aliases.governorate.muscat,'مسقط');assert.equal(records.find(r=>r.datasetType==='news_reports').provenance.period.coverage,'2025-H1');assert.equal(records.find(r=>r.datasetType==='commercial_registrations').provenance.period.coverage,'2026-Q1');});
test('idempotent import, filters, injection rejection and atomic publication',async()=>{await service.reimport();await service.reimport();assert.equal(await Record.countDocuments(),3);let result=await service.query({governorate:'مسقط',wilayat:'بوشر'});assert.equal(result.results[0].rowCount,3);assert.equal(result.results[0].metrics[0].value,null);assert.equal(result.results[0].metrics[0].knownPartialSum,2);assert.equal(result.results[0].metrics[0].missingOrNonNumeric,1);assert.equal((await service.query({wilayat:'صلالة'})).status,'no_matching_data');await assert.rejects(service.query({governorate:{$ne:null}}));await State.create({_id:'import-lock'});await assert.rejects(service.reimport(),{status:409});await State.deleteOne({_id:'import-lock'});assert.equal((await service.query({})).results[0].rowCount,3);assert.equal((await service.context('الشركات الناشئة في 2030')).status,'no_matching_data');});
test('internal endpoint fails closed; public data has no user ownership mutation',async()=>{let calls=0;const app=express();app.use(createOmanDataRouter({reimport:async()=>{calls++;return {ok:true};}},{OMAN_DATA_IMPORT_TOKEN:'x'.repeat(40)}));assert.equal((await request(app).post('/reimport')).status,403);assert.equal((await request(app).post('/reimport').set('Authorization','Bearer '+ 'x'.repeat(40))).status,200);assert.equal(calls,1);const disabled=express();disabled.use(createOmanDataRouter({},{}));assert.equal((await request(disabled).post('/reimport')).status,503);});
test('structured context separate and system instruction unchanged',()=>{const body=buildSmartAssistantRequest('سؤال',[],[],null,[],{status:'unavailable',results:[]});assert.equal(body.systemInstruction.parts[0].text,RIADATECH_SYSTEM_PROMPT);assert.ok(body.contents[0].parts[0].text.startsWith('[STRUCTURED_OMAN_DATA_CONTEXT]'));assert.equal(body.contents.at(-1).parts[0].text,'سؤال');});
test('failed write retains active snapshot and releases import lock',async()=>{
 const before=(await State.findById('active').lean()).payload.datasetIds;
 const failing=createOmanDataService({Record:{bulkWrite:async()=>{throw new Error('simulated write failure');}},State,directory:dir});
 await assert.rejects(failing.reimport(),/simulated write failure/);
 assert.deepEqual((await State.findById('active').lean()).payload.datasetIds,before);
 assert.equal(await State.findById('import-lock'),null);
});
