// Curated public pages only. This is not a crawler; linked pages are never followed.
export const OFFICIAL_SOURCES = [
  ['https://gov.om/w/create-new-commercial-register-for-limited-liability-company', ['starting_business','commercial_registration','legal_forms'], 'وزارة التجارة والصناعة وترويج الاستثمار'],
  ['https://gov.om/w/apply-for-commercial-registration-for-one-person-company', ['starting_business','commercial_registration','legal_forms'], 'وزارة التجارة والصناعة وترويج الاستثمار'],
  ['https://gov.om/w/renew-commercial-register', ['commercial_registration','renewal'], 'وزارة التجارة والصناعة وترويج الاستثمار'],
  ['https://gov.om/w/update-commercial-registration-data', ['commercial_registration','amendment'], 'وزارة التجارة والصناعة وترويج الاستثمار'],
  ['https://gov.om/w/create-commercial-register-for-home-business', ['home_business','starting_business'], 'وزارة التجارة والصناعة وترويج الاستثمار'],
  ['https://gov.om/w/get-investment-license', ['investment_license'], 'وزارة التجارة والصناعة وترويج الاستثمار'],
  ['https://gov.om/w/get-a-license-to-practice-an-activity', ['activity_license'], 'المؤسسة العامة للمناطق الصناعية – مدائن'],
  ['https://gov.om/w/get-entrepreneurship-card', ['riyada_card','sme_support'], 'هيئة تنمية المؤسسات الصغيرة والمتوسطة'],
  ['https://gov.om/w/register-for-income-tax-', ['income_tax','tax_registration'], 'جهاز الضرائب'],
  ['https://gov.om/w/register-for-vat%09-1', ['vat','tax_registration'], 'جهاز الضرائب'],
  ['https://tms.taxoman.gov.om/portal/ar/income-tax-faqs', ['income_tax','tax_registration'], 'جهاز الضرائب'],
  ['https://tms.taxoman.gov.om/portal/ar/vat-faqs', ['vat'], 'جهاز الضرائب'],
  ['https://www.sme.gov.om/servicedetails/?ID=0', ['riyada_card','sme_support'], 'هيئة تنمية المؤسسات الصغيرة والمتوسطة'],
  ['https://www.sme.gov.om/servicedetails/?ID=4', ['sme_support','mentoring'], 'هيئة تنمية المؤسسات الصغيرة والمتوسطة'],
  ["https://www.tejarah.gov.om/ar/invest", ["business_setup", "starting_business", "commercial_registration"], "وزارة التجارة والصناعة وترويج الاستثمار"],
  ["https://gov.om/w/create-commercial-register-for-individual-trader", ["starting_business", "commercial_registration", "legal_forms"], "وزارة التجارة والصناعة وترويج الاستثمار"],
  ["https://gov.om/w/create-new-commercial-register-for-general-partnership", ["starting_business", "commercial_registration", "legal_forms"], "وزارة التجارة والصناعة وترويج الاستثمار"],
  ["https://gov.om/w/get-commercial-registration-for-street-vendors", ["street_vendors", "commercial_registration"], "وزارة التجارة والصناعة وترويج الاستثمار"],
  ["https://gov.om/w/request-for-the-transfer-of-commercial-register-ownership", ["commercial_registration", "transfer"], "وزارة التجارة والصناعة وترويج الاستثمار"],
  ["https://gov.om/w/modify-commercial-register-data", ["commercial_registration", "amendment"], "وزارة التجارة والصناعة وترويج الاستثمار"],
  ["https://gov.om/w/register-commercial-representation-office", ["commercial_registration", "foreign_business"], "وزارة التجارة والصناعة وترويج الاستثمار"],
  ["https://gov.om/ar/w/get-a-license-to-practice-e-commerce-commercial-companies-", ["ecommerce", "activity_license"], "وزارة التجارة والصناعة وترويج الاستثمار"],
  ["https://gov.om/ar/w/get-a-license-to-practice-e-commerce-freelancers-", ["ecommerce", "activity_license"], "وزارة التجارة والصناعة وترويج الاستثمار"],
  ["https://gov.om/w/get-municipal-license-for-vehicles-6", ["municipal_license", "vehicle_license"], "محافظة جنوب الباطنة"],
  ["https://gov.om/w/get-advertising-license-6", ["municipal_license", "advertising_license"], "محافظة جنوب الباطنة"],
  ["https://gov.om/ar/w/get-license-for-printed-materials-and-publications", ["municipal_license", "advertising_license"], "بلدية مسقط"],
  ["https://gov.om/w/renew-entrepreneurship-card-2", ["riyada_card", "card_renewal"], "هيئة تنمية المؤسسات الصغيرة والمتوسطة"],
  ["https://gov.om/w/get-the-startup-entrepreneurship-card-1", ["startup_card", "sme_support"], "هيئة تنمية المؤسسات الصغيرة والمتوسطة"],
  ["https://tms.taxoman.gov.om/portal/ar/registration", ["tax_registration", "income_tax", "vat"], "جهاز الضرائب"],
  ["https://www.sme.gov.om/servicedetails/?ID=1", ["sme_support", "incubation"], "هيئة تنمية المؤسسات الصغيرة والمتوسطة"],
  ["https://www.sme.gov.om/servicedetails/?ID=2", ["sme_support", "training"], "هيئة تنمية المؤسسات الصغيرة والمتوسطة"],
  ["https://www.sme.gov.om/servicedetails/?ID=3", ["sme_support", "consulting"], "هيئة تنمية المؤسسات الصغيرة والمتوسطة"],
  ["https://www.sme.gov.om/servicedetails/?ID=5", ["sme_support", "craft_support"], "هيئة تنمية المؤسسات الصغيرة والمتوسطة"],
  ["https://www.sme.gov.om/servicedetails/?ID=6", ["sme_support", "franchise"], "هيئة تنمية المؤسسات الصغيرة والمتوسطة"],
  ["https://www.sme.gov.om/servicedetails/?ID=7", ["sme_support", "marketing"], "هيئة تنمية المؤسسات الصغيرة والمتوسطة"],
].map(([url, topics, authority]) => ({ url, topics, authority }));
